### ISSUE TITLE
Consecutive scans do not work properly

### ISSUE THREAD

**Issue by ImmortalZypther** [hax0kartik/wumiibo#1]
The first scan works to unlock the dungeons.
The second scan gives an error telling me to check the IP and the internet. 

I tried restarting the client but it didn't solve the issue. I also tried pressing start to remove the amiibo but it still gave the error.

It works if I restart the game entirely after unlocking the dungeons.

**Comment by ImmortalZypther** [comment]
Can't record but I can give you the text printed in the command prompt
```js
Reading Files. //I click "Emulate" for the first time to get into Mila's Ordeals.
Files parsed successfully.
Connecting to 3DS.
Connect succeeded
Connected.
Cmdid recieved 00110000
Cmdid recieved 00070000
Cmdid recieved 00180000
Cmdid 0x18 recievedCmdid recieved 00130040
Expected AppID 2B1A00: Our AppID 2990E02
0x13 Not Initialized
Cmdid recieved 000D0000
TagState 5 //This is the final line outputted once I was in Mila's Ordeals for the first time.
Cmdid recieved 000D0000 //These lines are outputted as soon as I entier the Mila's Ordeals amiibo scan menu for the _second_ time.
TagState 5
Cmdid recieved 00050040
Cmdid recieved 000D0000
TagState 2
Cmdid recieved 000D0000
TagState 3
Cmdid recieved 000D0000
TagState 3
Cmdid recieved 000D0000
TagState 3 //The line TagState 3 and the line preceeding it would repeat infinitely if I left the GUI alone without clicking "Emulate"
Reading Files. //I click "Emulate" for the second time while on the amiibo scan menu.
Files parsed successfully.
Connecting to 3DS.
Cmdid recieved 000D0000
TagState 3
Disconnected
Connect failed 
```

Here are my exact steps for anyone to recreate. 
These are assuming you have access to the “Dungeon” option in the Amiibo menu already.
1. Select Mila's Ordeals.
2. Input the encrypted and decrypted Celica amiibo file into Wumiibo along with the IP of your 3DS.
3. Hit Execute. This should take you to the menu where you can start exploring the dungeon.
4. Press B to get back to the menu where you select which ordeal you want to get into.
5. Repeat steps 1 through 3. On this repetition of Step 3, you will get the “Connect failed” output in the command prompt followed by an error message telling you to check the internet connection and IP.

For me, these steps consistently give the issue. 

Also, for clarification purposes: When I said “It works if I restart the game entirely after unlocking the dungeons”, I mean that multiple scans in a row work if you restart the game. Even just by closing it and reopening it, the scan will work once more.

I also tested with the non-gui version just to see if anything was different. The CMD output was exactly the same, so I chose not to repost it here.

My 3DS is a N2DS running Luma v10.1.3 and has the System Version 11.13.0-45U.
My Shadows of Valentia copy has the Title ID 00040000001B4100 and has the v1.1 update installed.

Hopefully this is enough information for you; if you need anything else, feel free to ask.

**Comment by hax0kartik** [comment]
This is indeed an issue, consecutive scans, without closing the app seems to not work.

**Comment by hax0kartik** [comment]
Fixed with new release.
