### ISSUE TITLE
No compatibility with Animal Crossing New Leaf

### ISSUE THREAD

**Issue by xlRYKOz** [hax0kartik/wumiibo#10]
Already checked on very games but the Animal Crossing New Leaf does not work correctly.

**Comment by hax0kartik** [comment]
I have multiple people who have confirmed acnl works. How can I repro  your issue?

**Comment by hax0kartik** [comment]
also n3ds or o3ds?

**Comment by xlRYKOz** [comment]
Hi. Thanks for replying. 
I'm using an OLD3DS without an NFC READER. Already checked on HAPPY HOME DESIGNER and it works correctly but NEW LEAF doesn't :(

**Comment by xlRYKOz** [comment]
> also n3ds or o3ds?

Hi. Thanks for replying.
I'm using an OLD3DS without an NFC READER. Already checked on HAPPY HOME DESIGNER and it works correctly but NEW LEAF doesn't :(

**Comment by hax0kartik** [comment]
Dis you get it to work?
