### ISSUE TITLE
Disney Infinity TBC Compatibility

### ISSUE THREAD

**Issue by LilG09-GH** [hax0kartik/wumiibo#101]
I know two people will want this, but can you add compatibility for Disney Infinity TBC? My guess is it'd be super easy, since Amiibos and Infinity Figures are basically the same...

If not, that's fine, this is kinda a meme request. But I also want to see how bad this game was again

**Comment by hax0kartik** [comment]
Hi, do you have any technical doumenation on how Disney Infinity works?

**Comment by LilG09-GH** [comment]
Not really, besides you need the figures to play the game, which needs a certain portal that isn't the amiibo portal

**Comment by SirLoopy** [comment]
The Infinity Portal makes use of the IR port for communication, and not the
built in RFID reader.

The Infinity Characters come in 3 different series, however the 3DS game is
only compatible with the 1.0 series. These use an RFID tag similar to the
Amiibo's but a different one.

There is some information along with Python scripts for the Infinity and
Skylander stuff: https://nfc.toys/workflow-inf.html

**Comment by LilG09-GH** [comment]
So, theoretically possible with Wumiibo, No?

**Comment by hax0kartik** [comment]
Nope, wumiibo is a rewrite of the NFC module. This, on the other hand, would require either patching the game or the IR module, which is out-of-scope for this project.
