### ISSUE TITLE
Yoshi's Woolly World doesn't work

### ISSUE THREAD

**Issue by Syko7956** [hax0kartik/wumiibo#11]
At first I used my old bins from the nfcbank and they crashed the moment I pressed the button combo. 
So I used your source and this time I got into the amiibo list. (Good progress)
But after choosing Mario.bin I crashed.

**Comment by hax0kartik** [comment]
Is this o3ds or n3ds?

**Comment by hax0kartik** [comment]
This is the most recent build https://discord.com/channels/356378901250834432/356383236705878036/751608268110954596
Please try.

**Comment by Syko7956** [comment]
N3DS. I'll let you know after I test.

**Comment by Syko7956** [comment]
Oh, you did Copy Message Link instead of Copy Link. Try again, please

**Comment by hax0kartik** [comment]
whoops. https://cdn.discordapp.com/attachments/356383236705878036/751706111828164638/0004013000004002.zip there you go, if it doesn't work, turn on logging and send me "wumiibo.txt" from the root of your sd card.

**Comment by Syko7956** [comment]
I can't even turn on Debugging to even send the log, sorry. Any option I press automatically crashes my 3DS. Can't even get to the list this time.

**Comment by Syko7956** [comment]
Just wanna confirm, in case you're worried if I set it up correctly, this DOES work for Fire Emblem Echoes and Wario Ware Gold perfectly fine.

**Comment by hax0kartik** [comment]
I just tested this on my own 3ds, and tyes this issue does seem to occur. Game crashes with svcBreak seemihnly called from the gfx thread(?)  which is really weird.

**Comment by Syko7956** [comment]
Sorta works now with the latest nightly build. I tried Mario, it backed out of the amiibo scan (might be from the button combo ending with Start?), I went back to the amiibo button and the scan still held so it automatically scanned Mario on the revisit. Tried Sonic and I crashed.

**Comment by hax0kartik** [comment]
Single scan seems to be working fine. Game crashes as soon as I change amiibos. Still trying to figure out why.

**Comment by Syko7956** [comment]
Just dropping by to confirm it seamlessly works. Good job, bro! This has come a long way
