### ISSUE TITLE
Kirby Planet Robobot ALMOST works

### ISSUE THREAD

**Issue by Syko7956** [hax0kartik/wumiibo#13]
With the shared discord nightly build given in the Yoshi submitted issue
I actually got farther. I can turn on debugging, and choose the amiibo. It's a unique issue where it visually looks softlocked but with enough patience, the sfx play the sequence very far apart (few minutes). The frame advances one frame every 30 seconds or so. 10 minutes in, the entire sfx played but Kirby was still clapping his first animation so I quit. Unfortunately even with debugging on, it just gave blank info. just dashes.

**Comment by hax0kartik** [comment]
I am also aware of this issue, however, fixing this game is on low priority since this is going to tough to figure out due to threading.

**Comment by hax0kartik** [comment]
Could you test this 
https://cdn.discordapp.com/attachments/356383236705878036/752191674901463131/settings.ini
https://cdn.discordapp.com/attachments/356383236705878036/752190855724531772/0004013000004002.zip

Drop the ini file on the root of your sd card and bring up wumiibo menu by pressing L + UP + START

**Comment by Syko7956** [comment]
I am absolutely amazed! It worked perfectly fine! GOOD JOB!

**Comment by hax0kartik** [comment]
Nice! thank you! I'll be closing this issue then.
