### ISSUE TITLE
Crash problem 

### ISSUE THREAD

**Issue by Bppuq** [hax0kartik/wumiibo#14]
When i close a game, the wumiibo menu open and my 3ds crash
Is an 3ds xl version

**Comment by hax0kartik** [comment]
Which game is this?

**Comment by Bppuq** [comment]
In every game, but it happen when wumiibo is off... without emulation, but anyways thanks for the emulator its good=)

**Comment by IrisHeartCPU** [comment]
it happens me too on some games, but rarely, i can remember it happening after using an amiibo succesfully on Fire Emblem IF (JP, english translated), when i exit the game, the wumiibo opens and my 3ds crash too, and with other many games even without opening or used wumiibo with that games (happened me barely like 4 times)
happens me too when i use the home menu.
