### ISSUE TITLE
amiibos not working

### ISSUE THREAD

**Issue by OrangwUWU** [hax0kartik/wumiibo#18]
So i have a bunch of amiibos and when i go to use one it says "File is encrypted, decrypt it using amiitool to use it with wumiibo" I can't find "amiitool" and as i have 318KB worth of amiibos i feel like finding/using amiitool would take a very long time so could you make a release version where its ok to use encrypted amiibos?

**Comment by Dimensional** [comment]
https://github.com/socram8888/amiitool
or
https://pypi.org/project/pyamiibo/
