### ISSUE TITLE
Crash with animal crossing new leaf

### ISSUE THREAD

**Issue by juandi46XD** [hax0kartik/wumiibo#19]
When I close the game animal crossing new leaf (just with this game) without using wumiibo(the same thing happens when I use it), the 2 screens freeze and I get the wumiibo menu on the lower screen but it stays frozen and forces me to turn off the console.

**Comment by hax0kartik** [comment]
please try the latest nightly, issue should be fixed
https://github.com/hax0kartik/wumiibo/suites/1185313145/artifacts/17380935
