### ISSUE TITLE
3ds wont boot

### ISSUE THREAD

**Issue by orangemn6** [hax0kartik/wumiibo#22]
I followed all of the instructions, but when I rebooted my 3ds  it wouldnt boot. I removed the files and it worked. Why does this happen?

**Comment by orangemn6** [comment]
i have v10.2 for luma is that the latest version?

**Comment by hax0kartik** [comment]
That is the latest version, yes. Do you have patches for other titiles too?

**Comment by orangemn6** [comment]
Yay it worked i just had to get rid of an emulator thanks
