### ISSUE TITLE
amiibo generator is missing a (few) amiibo

### ISSUE THREAD

**Issue by GuyInDogSuit** [hax0kartik/wumiibo#24]
Not sure if this on Ne3vin's end or yours, but I can't seem to call up a few files. Those being Dark Hammer Slam Bowser, Cat Mario, and Cat Peach. Now, the latter two, after googling all these, I know won't be out til next February, so we can't expect to have ANY data on those to begin with. The Bowser one was released in 2015. It's not a big deal to me, as it appears only a few games use it, and even then they pretty much have the same effect as the normal Hammer Slam Bowser (save for Skylanders, I think that one is a bit more useful).

Anyway, I might not necessarily **need** Bowser since I don't play Skylanders, but I thought I'd bring it to your attention.

**Comment by cheatfreak47** [comment]
Dark Hammer Slam Bowser shares its id with regular Hammer Slam Bowser, So no change is needed yet.
