### ISSUE TITLE
File could not be parsed.

### ISSUE THREAD

**Issue by B-rookie86** [hax0kartik/wumiibo#25]
It says "File could not be parsed.", I'm not sure if I'm doing something wrong or?

Edit: Found a way for it to work but the reason it wasn't working was putting the amiibo into folders makes it just not work??

**Comment by hax0kartik** [comment]
putting amiibos into folders should work. Could you give the full location where you put the amiibos?

**Comment by B-rookie86** [comment]
> putting amiibos into folders should work. Could you give the full location where you put the amiibos?

I made a folder called Wumiibo on the root of the sd and put a folder called amiibo into it with the bin files inside but it didn’t work, so I put the bin files into Wumiibo and now it works fine

**Comment by Sneethan** [comment]
@hax0kartik I have this problem too when i used the new app, is it because there were too many? Also, can you make the folders show the title of the game? I'm not a title id master yet.

**Comment by hax0kartik** [comment]
I checked my code again, this could have occurred if your file location was something very long... Also I have created a 3dsx which can generate amiibos directly from 3ds so you don't need to deal with titleids anymore.

**Comment by Sneethan** [comment]
> I checked my code again, this could have occurred if your file location was something very long... Also I have created a 3dsx which can generate amiibos directly from 3ds so you don't need to deal with titleids anymore.

Yes the problems happened when i used the new app

**Comment by Sneethan** [comment]
it names the folders after the titleids

**Comment by luna2709** [comment]
Idk if this will reopen the issue or not but I need to fix this.
I have the same issue "File could not be parsed" when I try to use the amiibo cards from the Sanrio Collection in Animal Crossing New Leaf, every other amiibos work but the Sanrio ones do not(these are for the vans that appear on the campsite), I really want to have the Sanrio Collection items on my city but it just keeps showing this issue.

**Comment by Sneethan** [comment]
Try making the amiibo with wumiibo heler
