### ISSUE TITLE
My 2DS will not boot

### ISSUE THREAD

**Issue by OliverTsubasaPt** [hax0kartik/wumiibo#27]
My 2DS will not boot when I put the files in the "titles" folder, it just won't.

**Comment by hax0kartik** [comment]
Do you have the latest luma version?

**Comment by OliverTsubasaPt** [comment]
I have version 10.2

**Comment by hax0kartik** [comment]
Try using this https://github.com/LumaTeam/Luma3DS/releases/tag/v10.2.1
