### ISSUE TITLE
Wumiibohelper.cia & list | Proposal

### ISSUE THREAD

**Issue by Ghost0159** [hax0kartik/wumiibo#30]
Hi, can you add wumiibohelper in cia, and also add a button from which we can see the amiibo with their images, be able to check them, then download them?
Otherwise, thank you very much for wumiibo.

**Comment by hax0kartik** [comment]
I somewhat implemented this in latest commit. 
https://gbatemp.net/attachments/1656565838344-png.315889/

**Comment by Ghost0159** [comment]
Okay, thank you very much
