### ISSUE TITLE
Can't create card set in Paper Jam

### ISSUE THREAD

**Issue by kendrieling** [hax0kartik/wumiibo#33]
I successfully made a card set for 1 amiibo in Paper Jam, but it freezes when I try to make more. It gets stuck on this screen.
![16091789979102116134174860355725](https://user-images.githubusercontent.com/74305669/103234580-078d4280-490e-11eb-8429-456c416858d5.jpg)

**Comment by GrewdonGaming21** [comment]
I recently was doing this too. Except my console crashed. I rebooted it and it started to work properly.

**Comment by hax0kartik** [comment]
Check issue #34.
