### ISSUE TITLE
Menu won’t open

### ISSUE THREAD

**Issue by broisthatyou** [hax0kartik/wumiibo#35]
My menu won’t open I did everything correctly and it won’t open

**Comment by Gecko4526** [comment]
Did u enable title patching?

**Comment by Mirageleader** [comment]
I enabled the title patching but I'm having the same error where it won't open...I tried to redownload the file too, still did not work. Everything appears to be in the right spot also, so I don't know what's going on.

**Comment by hax0kartik** [comment]
User error. Closing to clean up issues.

**Comment by SweetMerken** [comment]
I know this is supoust to be a closed issue, but i have de exact same problem and theres no apparent sollucion.
I follow the exact steps, put some amiibo bins, enable title patching, all in an old 3ds and the wumiibo menu just dont open.
If someone have a solution please let me know
