### ISSUE TITLE
Add a way to choose specific Amiibo in WumiiboHelper

### ISSUE THREAD

**Issue by GiraffeMan3125** [hax0kartik/wumiibo#36]
I want to get specific Amiibo without using my PC. Currently, WumiiboHelper downloads every Amiibo compatible, but that takes a bit, and most of the Amiibo downloaded, I will never use. Please add a new menu titled something like "Download Specific Amiibo" which displays a list of all Amiibo when you press A on an Amiibo, it downloads only that one.

**Comment by hax0kartik** [comment]
Same as isssue #30
