### ISSUE TITLE
Crash when launching some games without wireless connection

### ISSUE THREAD

**Issue by yoshi2999** [hax0kartik/wumiibo#4]
if I turn off that yellow light on my old 3DS XL and then either launch
-Mario Party the top 100 (game without amiibo function)
-Project X Zone 2
-Streetpass Plaza
and maybe some others but interestingly it doesn't crash for Mario Kart 7 and virtual consoles games.

turning on wireless connection then launching those games works fine (but it removes my dlc for streetpass plaza if I turn on wireless connection)

here a "saved crash dump" I did, idk if it's useful or has any of my personal information
[arm11.zip](https://github.com/hax0kartik/wumiibo/files/5138249/arm11.zip)

**Comment by hax0kartik** [comment]
Newest release no longer requires wifi to work :)
