### ISSUE TITLE
Hey Pikmin Writing/Reading Error

### ISSUE THREAD

**Issue by TFJ383** [hax0kartik/wumiibo#40]
The Pikmin and Olimar amiibo files have been giving me the Reading/Writing error whenever I attempt to scan them to unlock secret areas in the game:

"An error occurred while writing or reading amiibo data. Please try again."

I have attempted to do this with debugging off, as suggested, although debugging was never on in the first place in this case. I tried turning it on and off again for the sake of being thorough, but no dice there either.

**Comment by hax0kartik** [comment]
You need to first Initialize the card by going to amiibo settings.
