### ISSUE TITLE
N3DS Wont boot up

### ISSUE THREAD

**Issue by JuniorzGTZ** [hax0kartik/wumiibo#43]
I followed the exact instructions, now my N3DS wont boot up. When I remove wumiibo it boots up again like normal

**Comment by hax0kartik** [comment]
Are you using stock luma? 
Do you have any other folders in luma/tiles other than wummibo?

**Comment by JuniorzGTZ** [comment]
Im using Luma 10.2.1 3GX Loader Edition. And no I dont have any other folders other than wumiibo

**Comment by hax0kartik** [comment]
3GX Loader might be the problem. Try with stock luma.

**Comment by JuniorzGTZ** [comment]
Okay

**Comment by JuniorzGTZ** [comment]
Still doesnt work for some weird reason

**Comment by hax0kartik** [comment]
Join this discord and ping me https://discord.gg/hyuvmb9
