### ISSUE TITLE
Can i change the menu open code without the menu?

### ISSUE THREAD

**Issue by gergthewerg** [hax0kartik/wumiibo#44]
So my L and R buttons are broken and the replacements are gonna come in a while. Can I open the menu without the L button?

**Comment by hax0kartik** [comment]
https://github.com/hax0kartik/wumiibo/blob/master/wumiibo.ini Put this ini file in the root of your sd card and change the menu combo in the ini file.

**Comment by gergthewerg** [comment]
Thanks!

**Comment by gergthewerg** [comment]
> https://github.com/hax0kartik/wumiibo/blob/master/wumiibo.ini Put this ini file in the root of your sd card and change the menu combo in the ini file.

Nothing changed. I followed the instructions and Nothing changed
