### ISSUE TITLE
ACNL sanrio cards issue/can't change the amiibo scanned.

### ISSUE THREAD

**Issue by luna2709** [hax0kartik/wumiibo#45]
I try to scan amiibo cards from the Sanrio Collection and it gives me the "file could not be parsed" warning, while every other amiibo file works except the Sanrio ones (Chai, Rilla, Étoille[my favorite] and Chelsea). And since yesterday I cannot change the amiibo I want to scan, I scanned Pashminna once and since then I can't change the character, even if I choose another one she still appears as she was the one being scanned.

**Comment by hax0kartik** [comment]
Join my discord server, I'll need to debug this issue which will require some logs

**Comment by hax0kartik** [comment]
https://discord.gg/hyuvmb9

**Comment by hax0kartik** [comment]
Should be fixed with https://github.com/hax0kartik/wumiibo/commit/a2c24e08b527061172dace0bde7f2f83473c8f8d
