### ISSUE TITLE
0 figures compatible for some games

### ISSUE THREAD

**Issue by AutumnZero** [hax0kartik/wumiibo#47]
For my friend he was using Wumiibo for Animal Crossing: New Leaf Welcome Amiibo and when generating the amiibos it says that there are 0 figures compatible, only for this game and nothing else, is there a solution? 
![image](https://user-images.githubusercontent.com/82549561/162550130-84527dc7-67ff-4948-ae2d-4127131142cc.png)

**Comment by cooolgamer** [comment]
it work fine for me, seems fixed now
