### ISSUE TITLE
Wumiibo menu doesn't list every amiibo bin file 

### ISSUE THREAD

**Issue by agentbari2** [hax0kartik/wumiibo#48]
When there are a large number of bin files wumiibo doesn't list every .bin file, skipping after a certain point and going back to the start

**Comment by eku** [comment]
The file limit is 400, as seen in eb513097a2f99fab4f50267d86d527a9f4845ee9.

**Comment by hax0kartik** [comment]
As @eku mentioned, only 400 files are supported per folder. You can put the files in separate folders as a workaround.
