### ISSUE TITLE
Idea/question: Would it be possible to use this and make a code that makes the wiiu think its the gamepad but it is the 3ds?

### ISSUE THREAD

**Issue by SepticRedhead** [hax0kartik/wumiibo#52]
Basically if you hook up your 3ds to your wii u and use wumiibo it would be able to trick the wii u into thinking the emulated amiibo was a physical one coming from the wii u gamepad in a form of wii u connection mode that detects when it is connected to your wii u. Wumiibo then detects all the games you have on the system. thus allowing you to emulate amiibos on wii u using a 3ds and you would be able to download the amiibos compatible with each wii u game or there could be a list of games with wii u compatibility that you select from and get the amiibos from there.

**Comment by hax0kartik** [comment]
This is outright impossible, and outside the goals of wumiibo.
