### ISSUE TITLE
Wumiibo doesn't Work on N3DS XL

### ISSUE THREAD

**Issue by RinMaru** [hax0kartik/wumiibo#53]
Ive cleaned all ruminants of wumiibo from the sd card and uninstalled the wumiibo helper too then tried to reinstall via Universal updater and it just doesnt work. the menu doesnt pop up with the button combo so i cant get it on. also a download all would be great in wumiibo helper

**Comment by hax0kartik** [comment]
Downloqd wumiibohelper and then use the "Downlaod wumiibo" option.

**Comment by RinMaru** [comment]
> Download wumiibohelper and then use the "Download wumiibo" option.

ive tried and the button combo still wont work

**Comment by hax0kartik** [comment]
Join the discord https://discord.gg/hyuvmb9 I'll help you out there.
