### ISSUE TITLE
Fates Special Edition support

### ISSUE THREAD

**Issue by Quietninja0954** [hax0kartik/wumiibo#55]
In the compatibility log it shows Wumiibo can support fire emblem fates but it can only support Fire Emblem Fates: Birthright/Conquest. Could you add Fire Emblem Fates: Special Edition too?

**Comment by hax0kartik** [comment]
What is the title id for fates special edition?

**Comment by Quietninja0954** [comment]
0004000000179800

I just renamed one of the folders to make it work and if you’re wondering it works

**Comment by hax0kartik** [comment]
I have updated the json and wumiibohlper should now report your game as compatible. Please check and tell. Thanks!

**Comment by Quietninja0954** [comment]
![image](https://user-images.githubusercontent.com/66715677/180348565-c9cd3308-785a-49d5-8a06-89acfc469a7e.jpg)

It works perfectly
