### ISSUE TITLE
Shovel Knight Treasure Trove Not Showing in Wumiibo Helper

### ISSUE THREAD

**Issue by RandomMan25XX** [hax0kartik/wumiibo#57]
Despite the base game being supported, Treasure Trove (the version that includes all DLC for Shovel Knight) isn't showing up in the helper app to generate the amiibo files, given that the base game that is supported is the same as what's in Treasure Trove would there be an easy fix for this?

**Comment by RandomMan25XX** [comment]
I guess to tack on to this, saving amiibo progress doesn't seem to work

**Comment by Tretanium** [comment]
Bump

**Comment by hax0kartik** [comment]
Could you get me the titleid of the game?

**Comment by RandomMan25XX** [comment]
> Could you get me the titleid of the game?

So it seems that Wumiibo sees the digital version but not the physical version, the titleid for the physical version being 000400000017E100, I will test further with the digital version to see whether or not saving amiibo progress works

**Comment by hax0kartik** [comment]
I have added this tid to the jsons in the latest commit, this should fix the issue. Please confirm.

Open WumiiboHelper while connected to the internet and it should update the jsons automatically.
