### ISSUE TITLE
Suggestion: Automatically stop amiibo emulation via a setting 

### ISSUE THREAD

**Issue by swiffyjk** [hax0kartik/wumiibo#60]
Sometimes, I'll forget to force stop emulation and then the next time I use an amiibo, it is still emulating the previous.

If there were a setting with an amount of time the emulation is done for before it automatically stops, it would be greatly appreciated.

**Comment by hax0kartik** [comment]
This had been previously implemented, but it caused a lot of issues with other games, so I removed it. There is really no good way of knowing programmatically when the game  had finished scanning an amiibo.
