### ISSUE TITLE
Wumiibo fails to parse Amiibo files invalidate signatures

### ISSUE THREAD

**Issue by Adamillo** [hax0kartik/wumiibo#65]
Not sure if this is a bug or is intentional, but I just wanted to let you know that Amiibos with invalid signatures throw this error: "File could not be parsed."

**Comment by jetfire300** [comment]
im having the same issue and I have uninstalled it multiple times yet it never seems to work

**Comment by jetfire300** [comment]
finally got it working

**Comment by hax0kartik** [comment]
This is intentional.
