### ISSUE TITLE
Wumiibo not opening

### ISSUE THREAD

**Issue by CoverKun** [hax0kartik/wumiibo#68]
So i recently installed the plugin version of the roaslina menu and every since I did that Wumiibo wont open.

**Comment by hax0kartik** [comment]
plugin version of rosalina might not be compatible with wumiibo. I have never myself tested it out.

**Comment by plutxnium** [comment]
i tried using it with the luma plugin fork on animal crossing and the wumiibo menu wouldn't open.

**Comment by hax0kartik** [comment]
I just tried out the plugin fork of luma and it seems to work fine with amiibo settings. 
@plutxnium check if wumiibo menu opens in amiibo settings.
