### ISSUE TITLE
Wumiibo menu no longer opening since Luma 12.0

### ISSUE THREAD

**Issue by InsanePrimate** [hax0kartik/wumiibo#69]
As the title says. It would appear, that the newest Luma release is no longer compatible. Maybe something to do with the way it handles LayeredFs patching?

**Comment by hax0kartik** [comment]
With v12.0 you need to enable both game patching and loading external firms and module. Please do it manually for now. I'll update the build process and instructions soon.

**Comment by InsanePrimate** [comment]
> 

Both game patching and loading external firms and module options are enabled and the menu still doesn't open (tested in Metroid Samus Returns). I'll wait for a fix, thank you for having a look at it. :-)

**Comment by hax0kartik** [comment]
https://mega.nz/file/wANSiSrA#3zffZjJHaCFseYSCzgdcdLkoOsnOKpAbaydcaKqOx-c

Try installing wumiibo through this. Should work.

**Comment by hax0kartik** [comment]
Open up luma config menu and enable both game patching and loading external firms and modules.

**Comment by InsanePrimate** [comment]
> 

Both are enabled.

**Comment by hax0kartik** [comment]
I am not sure what's wrong with your installation, the same steps seem to work fine for me without any problem.

Also, open amiibo settings and then open rosalina menu, go to process lista nd check whether you have a process named wumiibo/nfc

**Comment by InsanePrimate** [comment]
> I am not sure what's wrong with your installation, the same steps seem to work fine for me without any problem.
> 
> Also, open amiibo settings and then open rosalina menu, go to process lista nd check whether you have a process named wumiibo/nfc

I do not have a process running named wumiibo/nfc... hmmm... could it be Fastboot (that is the only difference in the setup compared to the standard)

**Comment by hax0kartik** [comment]
> > I am not sure what's wrong with your installation, the same steps seem to work fine for me without any problem.
> > Also, open amiibo settings and then open rosalina menu, go to process lista nd check whether you have a process named wumiibo/nfc
> 
> I do not have a process running named wumiibo/nfc... hmmm... could it be Fastboot? (that is the only difference in the setup compared to the standard)

Would you happen to be in discord? It looks like it would take time to debug this issue..

**Comment by InsanePrimate** [comment]
> > > I am not sure what's wrong with your installation, the same steps seem to work fine for me without any problem.
> > > Also, open amiibo settings and then open rosalina menu, go to process lista nd check whether you have a process named wumiibo/nfc
> > 
> > 
> > I do not have a process running named wumiibo/nfc... hmmm... could it be Fastboot? (that is the only difference in the setup compared to the standard)
> 
> Would you happen to be on discord? It looks like it would take time to debug this issue..

Well I do have discord but i am not on your server.

**Comment by hax0kartik** [comment]
> > > > I am not sure what's wrong with your installation, the same steps seem to work fine for me without any problem.
> > > > Also, open amiibo settings and then open rosalina menu, go to process lista nd check whether you have a process named wumiibo/nfc
> > > 
> > > 
> > > I do not have a process running named wumiibo/nfc... hmmm... could it be Fastboot? (that is the only difference in the setup compared to the standard)
> > 
> > 
> > Would you happen to be on discord? It looks like it would take time to debug this issue..
> 
> Well I do have discord but i am not on your server.

Please do join, and ping me after doing so. My discord id is: Kartik#9392

**Comment by InsanePrimate** [comment]
> 

I tried joining (https://discord.com/invite/hyuvmb9) but it wouldn't let me XD nothing seems to be working on my end XD

**Comment by InsanePrimate** [comment]
System model: [New 2DS XL]

SysNAND version: [11.16.0-49E]

Entrypoint: [Fastboot v1.2]

Luma3DS version: [v12.0]

Luma3DS configuration/options:

Screen brightness: (4 )

Splash: ( Off)

PIN lock: ( Off)

New 3DS CPU: ( Off)

Homebrew autoboot (Off)

--

Enable loading external FIRMs and modules: (X)

Enable game patching: (X)

Redirect app. syscore threads to core2 ( )

Show NAND or user string in System Settings: (X)

Show GBA boot screen in patched AGB_FIRM: ( )

Set developer UNITINFO: ( )

Disable Arm11 exception handlers: ( )

Enable Rosalina on SAFE_FIRM: ( )

**Comment by hax0kartik** [comment]
> > 
> 
> I tried joining (https://discord.com/invite/hyuvmb9) but it wouldn't let me XD nothing seems to be working on my end XD

Please tell me your discord id

**Comment by InsanePrimate** [comment]
> 

I did send you a friend invite on discord.

**Comment by hax0kartik** [comment]
Closing as the issue was fixed.
User had fastboot which was configured to load luma from CTRNAND instead of SD.

**Comment by srwgin** [comment]
I delete luma boot.frim from sdcard and copy it to ctrnand
but it not work

**Comment by srwgin** [comment]
it work now
