### ISSUE TITLE
Metroid: Blast Ball does not work

### ISSUE THREAD

**Issue by cam1170** [hax0kartik/wumiibo#7]
N3DS. Should take most any amiibo and give a special or random costume. I tried Bowser, doesn't detect it. The game is free to play.

**Comment by hax0kartik** [comment]
Reproducible. Trying to fix.

**Comment by hax0kartik** [comment]
Fixed by commit b6593753f024d7b785f10e7641cff7d2ff94a602. https://github.com/hax0kartik/wumiibo/actions/runs/236770192 get this zip and replace the files in `sd:/luma/titles/0004013000004002/` with the ones in the zip.

Thank you for reporting!
