### ISSUE TITLE
Wumiibo Won't Open 

### ISSUE THREAD

**Issue by KosmicIdk** [hax0kartik/wumiibo#70]
Hi all. 

I've been trying as best i can to open the Wumiibo menu, and nothing i do will open it. I've disabled re-enabled it, I've downloaded the app and QR downloadable, and I've disabled re-enabled Game Patching. *Nothing* i do is working even after everything worked just fine before.

**Comment by hax0kartik** [comment]
Hey, have you tried the latest release of wumiibo?

**Comment by KosmicIdk** [comment]
I tried it and it didn't work unfortunately.

**Comment by hax0kartik** [comment]
Alright, please jump on this discord server so that i can help you out https://discord.gg/UHp6bMYN

**Comment by hax0kartik** [comment]
Issue resolved, user was not using wumiibohelper.
