### ISSUE TITLE
Doesn't work after updating to Luma 12.0.1

### ISSUE THREAD

**Issue by Slimo578** [hax0kartik/wumiibo#71]
After I updated to Luma 12.0.1 Wumiibo stopped working. When I press L+Down+Start nothing happens I already have the newest version of Wumiibo and also reinstalled it 
but it still doesn't work.

**Comment by Slimo578** [comment]
So I found out that in version 12.0.1 code.bin and exheader.bin loading doesn't work anymore and CXI loading should be used now so we just have to wait for an Wumiibo update.

**Comment by RinMaru** [comment]
> After I updated to Luma 12.0.1 Wumiibo stopped working. When I press L+Down+Start nothing happens I already have the newest version of Wumiibo and also reinstalled it but it still doesn't work.

Its needs to be updated to support the new standard they got rid of the old way
