### ISSUE TITLE
White screen on version 4.1 after download Wumiibo.

### ISSUE THREAD

**Issue by rynho** [hax0kartik/wumiibo#74]
I installed the wumiibohelper v4.1 using FBI scanning QR code, and download the wumiibo in the app, then screen turned white.  Assume this is related to Luma3DS version 12.1 update.

Rolled back to Luma3DS 12.0, luanch Wumiibo, and download again, still turn into white screen.

**Comment by softombre** [comment]
im having the same issue, wumiibo wasnt working after i updated to luma3DS 12.1 so i tried "download wumiibo" to see if thatd fix it but i got the white screen as well

**Comment by cobaltexzero** [comment]
Same here

**Comment by SuperMarioYAHOOYAHOO** [comment]
im pretty sure this represents download complete. on the instructions, i followed them still. on the white screen, i pressed b. and now im on the home screen. this is BUGGED OUT

**Comment by SuperMarioYAHOOYAHOO** [comment]
i think I'm right because i still get the wumibo menu upon pressing l +  start + dpad down.

**Comment by hax0kartik** [comment]
Please update your luma and wumiibo to the latest version.
