### ISSUE TITLE
Wumiibo doesn't show up upon pressing L + DOWN + START

### ISSUE THREAD

**Issue by DangerMage** [hax0kartik/wumiibo#78]
I enabled Game patching & Enable loading external FIRMs and modules

I go to wumiibo and toggle it to say enabled (though every time I try toggling it, it always says enabled press b to reboot)

I got a zelda amiibo from the generate amiibos for game button

I go into animal crossing new leaf and use the lamp thingy and then when it asks for an amiibo I press the left shoulder button, d-pad down, and start

then nothing happens.

I downloaded wumiibo from the universal updater, (says wumiibohelper.cia)

**Comment by hax0kartik** [comment]
Hi, please show me your luma config screen.

**Comment by adac7786** [comment]
![Screenshot_2](https://github.com/hax0kartik/wumiibo/assets/44790830/9e273449-b0c3-4d88-acfa-b1559864de5a)

**Comment by hax0kartik** [comment]
> ![Screenshot_2](https://user-images.githubusercontent.com/44790830/256800909-9e273449-b0c3-4d88-acfa-b1559864de5a.png)

Hi please hop on to this discord server so i can provide better help https://discord.gg/hyuvmb9

**Comment by DangerMage** [comment]
> hey man i just set up wumiibo for the first time and im encountering the same issue. latest firmware and luma. ill leave some screens in here for you.
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/44790830/256800723-38cd1c3d-a8fc-494c-bc42-0cd57cecba25.png) ![20230728_124241](https://user-images.githubusercontent.com/44790830/256800727-1b0887eb-e946-4336-80d0-637a7519009c.jpg) ![20230728_124321](https://user-images.githubusercontent.com/44790830/256800733-3baa6083-893d-4ee6-9665-4f597c734b3f.jpg)
> 
> the first amiibo folder was generated by the tool and the other folders are from the bulk download zip file.

Thanks a lot for taking over my issue instead of making your own.

**Comment by DangerMage** [comment]
> Hi, please show me your luma config screen.
![20230728_091618](https://github.com/hax0kartik/wumiibo/assets/57050396/a8e16cb4-a7c9-4393-9230-43f7714da5b2)

Here is my luma config screen.

**Comment by DangerMage** [comment]
> > Hi, please show me your luma config screen.
> > ![20230728_091618](https://user-images.githubusercontent.com/57050396/256862114-a8e16cb4-a7c9-4393-9230-43f7714da5b2.jpg)
> 
> Here is my luma config screen.
> 
> I just realized game patching isn't on so lemme turn that on real quick and see if it fixes it.

Game patching is now enabled but wumiibo still doesn't work.

**Comment by hax0kartik** [comment]
Please join that discord link as well so i can help you out

**Comment by DangerMage** [comment]
Fixed, Didn't press the download button after launching the wumiibo helper thingy from universal downloader
