### ISSUE TITLE
can you please explain what you need to do if its doesn't work wit a 3dsxl without sending a link for discord (i dont have discord)

### ISSUE THREAD

**Issue by j1sp** [hax0kartik/wumiibo#79]
just tell me please. because when i finish it it says verification failed, download menually.

**Comment by hax0kartik** [comment]
It could be a variety of reasons, but most likely you have a outdated luma. Update your luam ans try again.

**Comment by j1sp** [comment]
no i have the latest version already and it just doesn't work

**Comment by hax0kartik** [comment]
Show me a photo of your luma config screen(both top and bottom) and a photo of your /luma/sysmodules folder

**Comment by j1sp** [comment]
![Uploading IMG_2761.jpeg…]()

**Comment by j1sp** [comment]
![WIN_20230802_12_42_14_Pro](https://github.com/hax0kartik/wumiibo/assets/140956672/072e0c4f-d422-4dcf-b278-51728f43ce22)

**Comment by hax0kartik** [comment]
> ![WIN_20230802_12_42_14_Pro](https://user-images.githubusercontent.com/140956672/257788715-072e0c4f-d422-4dcf-b278-51728f43ce22.jpg)

I don't know how but you're booting from ctrnand check if you have a boot.firm file on the toot of your sd card.

**Comment by j1sp** [comment]
![WIN_20230802_14_06_35_Pro](https://github.com/hax0kartik/wumiibo/assets/140956672/ee9e6d20-c10f-41a1-befd-0a223e294cc8)

**Comment by j1sp** [comment]
thx it worked
