### ISSUE TITLE
50 Files

### ISSUE THREAD

**Issue by NavyivanMX** [hax0kartik/wumiibo#8]
Hi, It Works Perfect in Metroid and Ace Combat Thank you

When you pick a bin file, it only appear 50 bins. Can you make up to 128?

**Comment by hax0kartik** [comment]
With the latest commit I have added folder support to wumiibo, so you can now sort your amiibos into folders. You can also create a folder inside folder and hence there is no limit really left.

**Comment by NavyivanMX** [comment]
Thank you

**Comment by hacker1024** [comment]
Just to clarify - there's still a 50-file limit in a single directory?

**Comment by NavyivanMX** [comment]
You can put up to 49 files into a Sub/Folder
